### PR TITLE
Fix #210 #207 #203(#202)

### LINKED ISSUE #203: Client Side Crash - Incubator + Syringe with all Viral Agents (creating Black Death Potion)
Hello, 

Upon attempting to create a Black Death Potion, a client side crash occurs. After extracting and purifying the blood with all viral agents placing the syringe in the incubator crashes the client. 

Crash Report Attached.

[message.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/4876498/message.txt)

Thanks,

-Boxers41

### LINKED ISSUE #207: real issue or anything else? incubator
Anotación 2020-08-27 032530
chorus fruit slot is getting a duplicate in the first slot of potions, not allowing you to use 3 potions with chorus fruit for mutation

### LINKED ISSUE #210: Issue: poison, wither, and weakness virus shows no symptoms
Forge 14.23.5.2847
Genetics Reborn v1.29
Other mods inserted are Hwyla 1.8.26-B41, InventoryTweaks-1.63, jei 4.15.0.268, journeymap 5.5.5, NBTEdit-0.7, and Optifine HD U E3

Thank you for considering my report.
Some viruses does not seem to trigger any potion effects. I checked the NBT using the NBTEdit mod and found some Strings with name of the virus under ForgeCaps>geneticsreborn:genes, so I am assuming that I successfully infected a mob with a virus. However, they don't seem to show any symptoms (like flambe does immediately) even after waiting for couple of minutes. My friends with different environment are facing identical error.

Is this intentional, or is it glitched?

### PR DESCRIPTION
**Pull request by turtton**

### CODE REVIEW

**Comment by turtton** [comment]
My first commit named "Remove potionReset(it looks always false)" fixed #210 
I'm sorry for the confusing message.

**Review by clubpetey — COMMENTED** [review]
The bulk of this is good updates, thank you.  

However, I want to open a discussion on the potion timing.  My gut answer is to not make those changes in the system.  But let me explain.  

The theory behind the 110 ticks for a potion renewal vs. 50 is that for performance reasons potion updates are checked only once every two seconds (40 ticks).  If due to game lag, tick 40 is missed/skipped for some reason, then hopefully the tick at 80 would be processed.  This is done on purpose to make sure the potion effect does not "flicker" on/off every 2 second under server load, or drop all together. I have two chances to recheck the effect activation before the client  drops the effect.

The potionReset value is used for specific effects that were written to have long effect time on purpose.  Rather than checking every 40 ticks for the potion to be renewed, these are checked every 1800 ticks. Because the potion effect is supposed to last 2400 ticks.

These are all just my opinion, of course, if you changed the effect time of blindness, slowness, etc because you felt they should be the same length as the other potion effects, I could open that discussion.

**Comment by turtton** [comment]
I couldn't think about game lag. I will restore that soon.

However, I can't still understand why negative potion effect durations are long. Do these mean something like an after-effect?

**Comment by turtton** [comment]
And these effects will be delay max 90 seconds behind infecting viruses.

**Comment by turtton** [comment]
Potion timings work as before. 

I'd be happy to hear what you think about the above issues.

**Comment by clubpetey** [comment]
The reason for the long timers is the way viruses work.  The design is that drinking milk can temporarily avoid the effects, so viruses apply their effect for 10 seconds, every 10 seconds.  If you drink milk with 9 seconds left, you will get 9 seconds virus-free before the gene-check returns and re-applies the status effect.

In theory you can keep drinking milk until you can brew or get to a cure potion.

**Pull request merged**
